using UnityEngine;
using UnityEngine.SceneManagement;

public class SceneChange : MonoBehaviour
{
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    // public void LoadScene(string SceneName)
    // {
    //     SceneManager.LoadScene("SceneName");
    // }

    public void EnterInstructions()
    {
        SceneManager.LoadScene("Instructions");
    }

    public void StartGame()
    {
        SceneManager.LoadScene("SeedOne");
    }

    public void PlayAgain()
    {
        SceneManager.LoadScene("TitlePage");
    }
}
